OLED.init(128, 64)
basic.forever(function () {
    OLED.clear()
    OLED.writeString("světlo")
    OLED.writeNum(Environment.ReadLightIntensity(AnalogPin.P1))
    OLED.newLine()
    OLED.writeString("teplota")
    OLED.writeNum(Environment.octopus_BME280(Environment.BME280_state.BME280_temperature_C))
    OLED.newLine()
    OLED.writeString("vlhkost vzduchu")
    OLED.writeNum(Environment.dht11value(Environment.DHT11Type.DHT11_humidity, DigitalPin.P15))
    OLED.newLine()
    OLED.writeString("vlhkost kůže")
    OLED.writeNum(Environment.ReadSoilHumidity(AnalogPin.P2))
    OLED.newLine()
    OLED.writeString("vzdálenost")
    OLED.writeNum(Environment.sonarbit_distance(Environment.Distance_Unit.Distance_Unit_cm, DigitalPin.P1))
    basic.pause(1000)
})
