OLED.init(128, 64)
basic.forever(function () {
    OLED.clear()
    OLED.writeString("světlo")
    OLED.writeNum(Environment.ReadLightIntensity(AnalogPin.P1))
    OLED.newLine()
    OLED.newLine()
    OLED.writeString("teplota")
    OLED.writeNum(Environment.octopus_BME280(Environment.BME280_state.BME280_temperature_C))
    OLED.newLine()
    OLED.writeString("vlhkost")
    OLED.writeNum(Environment.dht11value(Environment.DHT11Type.DHT11_humidity, DigitalPin.P15))
    OLED.newLine()
    OLED.writeString("hloubka")
    OLED.writeNum(Environment.ReadWaterLevel(AnalogPin.P2))
    basic.pause(10000)
})
